### ISSUE TITLE
Error log di CMD

### ISSUE THREAD

**Issue by dzakijo1** [ItzNgga/wa-bot.js#4]
![image](https://user-images.githubusercontent.com/47619660/93660787-ad622300-fa7c-11ea-898e-05130fb2f884.png)

ini error kenapa ya? di cmdnya ga ada log nya padahal udah run dan kirim pesan, stuck disitu cmdnya

**Comment by ItzNgga** [comment]
> ![image](https://user-images.githubusercontent.com/47619660/93660787-ad622300-fa7c-11ea-898e-05130fb2f884.png)
> 
> ini error kenapa ya? di cmdnya ga ada log nya padahal udah run dan kirim pesan, stuck disitu cmdnya

Coba buka settings/setting.json

Periksa mtc/banchat true, jika true ganti ke false

**Comment by dzakijo1** [comment]
lah masih belom bisa si di ane :v
