### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by idkmew** [ItzNgga/wa-bot.js#7]
Hi, knp ya pas udah di npm start malah stuck di [INFO] Bot Started!

**Comment by Cahyo224** [comment]
> Hi, knp ya pas udah di npm start malah stuck di [INFO] Bot Started!

ngestucknya berapa lama tuh

**Comment by idkmew** [comment]
> > Hi, knp ya pas udah di npm start malah stuck di [INFO] Bot Started!
> 
> ngestucknya berapa lama tuh

yah anggapannya program tidak berjalan gitu

**Comment by itzngga** [comment]
> > > Hi, knp ya pas udah di npm start malah stuck di [INFO] Bot Started!
> > 
> > 
> > ngestucknya berapa lama tuh
> 
> yah anggapannya program tidak berjalan gitu

Ada 3 kemungkinan :
1. nomor sAdmin belum diganti di settings
2. banchat masih menyala/mtc di settings
3. prefix yg invalid seperti : "?"

**Comment by idkmew** [comment]
> > > > Hi, knp ya pas udah di npm start malah stuck di [INFO] Bot Started!
> > > 
> > > 
> > > ngestucknya berapa lama tuh
> > 
> > 
> > yah anggapannya program tidak berjalan gitu
> 
> Ada 3 kemungkinan :
> 
> 1. nomor sAdmin belum diganti di settings
> 2. banchat masih menyala/mtc di settings
> 3. prefix yg invalid seperti : "?"

hmmm mungkin sih, tapi kalau nomor admin sih udah bang, dan banchat masih menyala maksudnya gmna ya, and apakah ^ termasuk invalid prefix?

**Comment by idkmew** [comment]
> > > > Hi, knp ya pas udah di npm start malah stuck di [INFO] Bot Started!
> > > 
> > > 
> > > ngestucknya berapa lama tuh
> > 
> > 
> > yah anggapannya program tidak berjalan gitu
> 
> Ada 3 kemungkinan :
> 
> 1. nomor sAdmin belum diganti di settings
> 2. banchat masih menyala/mtc di settings
> 3. prefix yg invalid seperti : "?"

Dan btw
case '@6289654471026':
                        await client.sendTextWithMentions(chatId, `Hai @${serial.match(/\d+/g)}, ada yang bisa saya bantu? ${prefix}help untuk melihat list perintah :D`)
                        break
Disitu apakah nomor BOT? atau Nomor Admin ya?

**Comment by itzngga** [comment]
> Ada 3 kemungkinan :
> 
> 1. nomor sAdmin belum diganti di settings
> 2. banchat masih menyala/mtc di settings
> 3. prefix yg invalid seperti : "?"

hmmm mungkin sih, tapi kalau nomor admin sih udah bang, dan banchat masih menyala maksudnya gmna ya, and apakah ^ termasuk invalid prefix?

tidak termasuk invalid prefix, dan banchat/mtc masih true di setting.json

jika masih true ubah ke false

**Comment by itzngga** [comment]
> > > > > Hi, knp ya pas udah di npm start malah stuck di [INFO] Bot Started!
> > > > 
> > > > 
> > > > ngestucknya berapa lama tuh
> > > 
> > > 
> > > yah anggapannya program tidak berjalan gitu
> > 
> > 
> > Ada 3 kemungkinan :
> > 
> > 1. nomor sAdmin belum diganti di settings
> > 2. banchat masih menyala/mtc di settings
> > 3. prefix yg invalid seperti : "?"
> 
> Dan btw
> case '@6289654471026':
> await client.sendTextWithMentions(chatId, `Hai @${serial.match(/\d+/g)}, ada yang bisa saya bantu? ${prefix}help untuk melihat list perintah :D`)
> break
> Disitu apakah nomor BOT? atau Nomor Admin ya?

nomor botnya

**Comment by idkmew** [comment]
> > > > > > Hi, knp ya pas udah di npm start malah stuck di [INFO] Bot Started!
> > > > > 
> > > > > 
> > > > > ngestucknya berapa lama tuh
> > > > 
> > > > 
> > > > yah anggapannya program tidak berjalan gitu
> > > 
> > > 
> > > Ada 3 kemungkinan :
> > > 
> > > 1. nomor sAdmin belum diganti di settings
> > > 2. banchat masih menyala/mtc di settings
> > > 3. prefix yg invalid seperti : "?"
> > 
> > 
> > Dan btw
> > case '@6289654471026':
> > await client.sendTextWithMentions(chatId, `Hai @${serial.match(/\d+/g)}, ada yang bisa saya bantu? ${prefix}help untuk melihat list perintah :D`)
> > break
> > Disitu apakah nomor BOT? atau Nomor Admin ya?
> 
> nomor botnya

dan bang kalau saat program WA BOT udah gagal dan kita ingin mengulang jadi ibarat kyk mereset dan mengedit dari awal supaya programnya bisa normal lagi gitu gmna ya, ap yang harus dihapus?

**Comment by itzngga** [comment]
> > > > > > > Hi, knp ya pas udah di npm start malah stuck di [INFO] Bot Started!
> > > > > > 
> > > > > > 
> > > > > > ngestucknya berapa lama tuh
> > > > > 
> > > > > 
> > > > > yah anggapannya program tidak berjalan gitu
> > > > 
> > > > 
> > > > Ada 3 kemungkinan :
> > > > 
> > > > 1. nomor sAdmin belum diganti di settings
> > > > 2. banchat masih menyala/mtc di settings
> > > > 3. prefix yg invalid seperti : "?"
> > > 
> > > 
> > > Dan btw
> > > case '@6289654471026':
> > > await client.sendTextWithMentions(chatId, `Hai @${serial.match(/\d+/g)}, ada yang bisa saya bantu? ${prefix}help untuk melihat list perintah :D`)
> > > break
> > > Disitu apakah nomor BOT? atau Nomor Admin ya?
> > 
> > nomor botnya
> 
> dan bang kalau saat program WA BOT udah gagal dan kita ingin mengulang jadi ibarat kyk mereset dan mengedit dari awal supaya programnya bisa normal lagi gitu gmna ya, ap yang harus dihapus?

Saat ini blm ada tpi bisa di manual kan di setting.json dan semua json yg store data di clear dengan hati2

**Comment by idkmew** [comment]
> > > > > > > > Hi, knp ya pas udah di npm start malah stuck di [INFO] Bot Started!
> > > > > > > 
> > > > > > > 
> > > > > > > ngestucknya berapa lama tuh
> > > > > > 
> > > > > > 
> > > > > > yah anggapannya program tidak berjalan gitu
> > > > > 
> > > > > 
> > > > > Ada 3 kemungkinan :
> > > > > 
> > > > > 1. nomor sAdmin belum diganti di settings
> > > > > 2. banchat masih menyala/mtc di settings
> > > > > 3. prefix yg invalid seperti : "?"
> > > > 
> > > > 
> > > > Dan btw
> > > > case '@6289654471026':
> > > > await client.sendTextWithMentions(chatId, `Hai @${serial.match(/\d+/g)}, ada yang bisa saya bantu? ${prefix}help untuk melihat list perintah :D`)
> > > > break
> > > > Disitu apakah nomor BOT? atau Nomor Admin ya?
> > > 
> > > 
> > > nomor botnya
> > 
> > 
> > dan bang kalau saat program WA BOT udah gagal dan kita ingin mengulang jadi ibarat kyk mereset dan mengedit dari awal supaya programnya bisa normal lagi gitu gmna ya, ap yang harus dihapus?
> 
> Saat ini blm ada tpi bisa di manual kan di setting.json dan semua json yg store data di clear dengan hati2

semua json yg store data di clear dengan hati2 bang mau nanya semua json store data itu dibagian mana ya, dan mohon maaf karena saya terlalu banyak bertana :'(

**Comment by idkmew** [comment]
terima kasih bang, dan mau bertanya nih, untuk akses menu premium gimana ya

**Comment by itzngga** [comment]
close ya krn sdh solved
